// react-client/src/pages/GoalDetailsPage/GoalDetailsPageComponent/GoalButtons.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import LoadingButton from '../../../sharedComponents/forms/LoadingButton';
import {
  UPDATE_GOAL_LEDGER_BUTTON,
  DELETE_GOAL_BUTTON,
} from '../../../redux/buttonTypes';
import ToggleButtonModule from '../../../sharedComponents/ToggleButtonModule';

interface IProps {
  isStarted: boolean;
  isOwner: boolean;
  isActive: boolean;
  loadingButton: string;
  deleteGoal: () => void;
  handleSave: () => void;
}

//Buttons for goal page - buttons shown are dependent on who is viewing goal and time of goal
const GoalButtons: React.FC<IProps> = ({
  isStarted,
  isOwner,
  isActive,
  loadingButton,
  deleteGoal,
  handleSave,
}) => {
  return (
    <React.Fragment>
      {/* SaveButton */}
      {isStarted && isOwner && isActive && (
        <React.Fragment>
          {/* TODO - LOADING SPINNER AND ALERT*/}
          <LoadingButton
            className='btn btn-block btn-primary'
            isInput={false}
            handleClick={handleSave}
            message='Save Goal'
            isLoading={loadingButton === UPDATE_GOAL_LEDGER_BUTTON}
          />
          <p className='lr-border' />
        </React.Fragment>
      )}
      {/* Modify Button */}
      {isActive && (
        <React.Fragment>
          <Link to='/updategoal' className='btn btn-block btn-primary center'>
            Modify Goal
          </Link>
        </React.Fragment>
      )}
      {/* Delete Button */}
      <ToggleButtonModule
        handleClick={deleteGoal}
        isLoading={loadingButton === DELETE_GOAL_BUTTON}
        topButton='Delete Goal'
      >
        <span className='alert lr-border'>
          Are you sure you want to delete this goal? Deletions cannot be undone.
        </span>
      </ToggleButtonModule>
    </React.Fragment>
  );
};

export default GoalButtons;

// client/src/app/goal/goal-page/goal-buttons/goal-buttons.component.ts
import { Component, OnInit } from '@angular/core';
import { GoalService } from '../../goal.service';

@Component({
  selector: 'app-goal-buttons',
  templateUrl: './goal-buttons.component.html',
  styleUrls: ['./goal-buttons.component.css'],
})
export class GoalButtonsComponent implements OnInit {
  isStarted: boolean;
  isActive: boolean;
  isOwner: boolean;
  deleteToggle = false;

  constructor(private goalService: GoalService) {}

  ngOnInit(): void {
    this.isStarted = this.goalService.isStarted;
    this.isActive = this.goalService.isActive;
    this.isOwner = true; // TODO
  }

  saveGoal(): void {
    this.goalService.saveTracker();
  }

  deleteGoal(): void {
    this.goalService.deleteGoal();
  }

  setDeleteToggle(): void {
    this.deleteToggle = !this.deleteToggle;
  }
}

<ng-container *ngIf="isStarted && isActive && isOwner">
  <button class="btn btn-block btn-primary" (click)="saveGoal()">
    Save Goal
  </button>
  <p class="lr-border"></p>
</ng-container>
<ng-container *ngIf="isActive">
  <a href="" class="btn btn-block btn-primary center">
    Modify Goal
  </a>
  <p *ngIf="!deleteToggle" class="lr-border"></p>
</ng-container>
<button
  *ngIf="!deleteToggle"
  class="btn btn-block btn-primary"
  (click)="setDeleteToggle()"
>
  Delete Goal
</button>
<hr />
<ng-container *ngIf="deleteToggle">
  <span class="alert lr-border">
    Are you sure you want to delete this goal? Deletions cannot be undone.
  </span>
  <button class="btn btn-primary btn-split" (click)="setDeleteToggle()">
    No
  </button>
  <button class="btn btn-danger btn-split" (click)="deleteGoal()">
    Yes
  </button>
</ng-container>
