// client/src/app/goal/goal-page/goal-info/goal-info.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { IGoal } from '../../../shared/models/goal';
import * as moment from 'moment';
import { GoalService } from '../../goal.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-goal-info',
  templateUrl: './goal-info.component.html',
  styleUrls: ['./goal-info.component.css'],
})
export class GoalInfoComponent implements OnInit {
  goal: IGoal;
  time: number;
  isStarted: boolean;
  value: number;
  record: any[];
  topLeftTag = 'Start Date: ';
  topLeftMsg: string = null;
  topRightTag: string = null;
  topRightMsg: string = null;
  middleLeftTag: string = null;
  middleLeftMsg: string = null;
  middleRightTag: string = null;
  middleRightMsg: string = null;
  bottomLeftTag: string = null;
  bottomLeftMsg: string = null;
  bottomRightTag: string = null;
  bottomRightMsg: string = null;

  constructor(private goalService: GoalService) {}

  ngOnInit(): void {
    this.goal = this.goalService.goal;
    this.time = this.goalService.time;
    this.isStarted = this.goalService.isStarted;
    this.record = this.goalService.record;
    this.goalService.value.subscribe((value) => {
      this.value = value;
      this.formatMessages();
    });
  }

  formatMessages(): void {
    const { type, duration, startDate, units, total } = this.goal;
    this.topLeftMsg = `${moment.utc(startDate).format('MMMM Do, YYYY')}`;

    if (this.isStarted) {
      if (type === 0) {
        // passfail
        this.middleLeftTag = 'Success To Date: ';
        this.middleLeftMsg = `${this.value} / ${
          this.time > duration ? this.record.length : this.time + 1
        } (${Math.round((this.value / (this.time + 1)) * 100)}%)`;
        this.bottomLeftTag = 'Success Total: ';
        this.bottomLeftMsg = `${this.value} / ${
          this.record.length
        } (${Math.round((this.value / this.record.length) * 100)}%)`;
      } else if (type === 1) {
        // total
        this.topRightTag = this.time === duration ? 'Duration: ' : 'Day: ';
        this.topRightMsg =
          this.time === duration
            ? `${duration} days`
            : `${this.time + 1} / ${duration}`;
        this.middleLeftTag = 'Total: ';
        this.middleLeftMsg = `${this.value} / ${total} ${units}`;
        this.middleRightTag = 'Goal Completion: ';
        this.middleRightMsg = `${Math.round((this.value / total) * 100)}%`;
      } else if (type === 2) {
        // difference
        this.topRightTag = this.time === duration ? 'Duration: ' : 'Day: ';
        this.topRightMsg =
          this.time === duration
            ? `${duration} days`
            : `${this.time + 1} / ${duration}`;
        this.middleLeftTag = 'Start: ';
        this.middleLeftMsg = `${this.record[0]} ${units}`;
        this.middleRightTag = 'Goal: ';
        this.middleRightMsg = `${total} ${units}`;
        this.bottomLeftTag = this.time === duration ? 'Final: ' : 'Current: ';
        this.bottomLeftMsg = `${this.record[0] + this.value} ${units}`;
        this.bottomRightTag = 'Change: ';
        this.bottomRightMsg = `${this.value > 0 ? '+' : ''}${
          this.value
        } ${units}`;
      }
    } else {
      this.topLeftTag = 'Begins: ';
      this.topRightTag = 'Duration: ';
      this.topRightMsg = `${duration} days`;
      if (type === 1) {
        this.middleLeftTag = 'Goal: ';
        this.middleLeftMsg = `${total} ${units}`;
      } else if (type === 2) {
        this.middleLeftTag = 'Start: ';
        this.middleLeftMsg = `${this.record[0]} ${units}`;
        this.middleRightTag = 'Goal:';
        this.middleRightMsg = `${total} ${units}`;
      }
    }
  }
}

<li *ngIf="this.goal.description" class="table-info lr-border">
  <span><strong>Description: </strong>{{ this.goal.description }}</span>
</li>
<li class="table-info lr-border">
  <div class="space-between">
    <span *ngIf="topLeftTag !== null">
      <strong>{{ topLeftTag }}</strong
      >{{ topLeftMsg }}
    </span>
    <span class="right" *ngIf="topRightTag !== null">
      <strong>{{ topRightTag }}</strong
      >{{ topRightMsg }}
    </span>
  </div>
</li>
<li class="table-info lr-border">
  <div class="space-between">
    <span *ngIf="middleLeftTag !== null">
      <strong>{{ middleLeftTag }}</strong
      >{{ middleLeftMsg }}
    </span>
    <span class="right" *ngIf="middleRightTag !== null">
      <strong>{{ middleRightTag }}</strong
      >{{ middleRightMsg }}
    </span>
  </div>
</li>
<li class="table-info lr-border">
  <div class="space-between">
    <span *ngIf="bottomLeftTag !== null">
      <strong>{{ bottomLeftTag }}</strong
      >{{ bottomLeftMsg }}
    </span>
    <span class="right" *ngIf="bottomRightTag !== null">
      <strong>{{ bottomRightTag }}</strong
      >{{ bottomRightMsg }}
    </span>
  </div>
</li>

// react-client/src/sharedComponents/goalCompPage/GoalInfo.tsx
import React from 'react';
import moment from 'moment';
import { getGoalScore } from '../../util/goalFunctions';
import { getGoalTime, cleanNumber } from '../../util/dateFunctions';
import { TGoal, EGoalType } from '../../types';
import { TableInfo, WhiteSpaceSpan } from '../styledComponents/Misc';

interface IProps {
  goal: TGoal;
  time: number;
  record: (number | null)[];
  isFinished: boolean;
}

//messaging to describe goal - varies greatly depending on type and time status
const GoalInfo: React.FC<IProps> = ({ goal, time, record, isFinished }) => {
  const {
    duration,
    startTime,
    description,
    units,
    target,
    type,
    initialValue,
  } = goal;
  const { isStarted } = getGoalTime(startTime, duration);
  const formattedDate = moment.utc(startTime).format('MMMM Do, YYYY');
  const formattedDateTime = moment
    .utc(startTime)
    .format('MMMM Do, YYYY, h:mm a');
  const score = cleanNumber(getGoalScore(type, record, initialValue));

  let topLeftTag = '';
  let topLeftMsg = '';
  let topRightTag = '';
  let topRightMsg = '';
  let middleLeftTag = '';
  let middleLeftMsg = '';
  let middleRightTag = '';
  let middleRightMsg = '';
  let bottomLeftTag = '';
  let bottomLeftMsg = '';
  let bottomRightTag = '';
  let bottomRightMsg = '';

  if (isFinished) {
    topLeftTag = 'Start Date: ';
    topLeftMsg = formattedDate;
    if (type === EGoalType.passfail) {
      middleLeftTag = 'Success Total: ';
      middleLeftMsg = `${score} / ${(duration * target) / 7} (${Math.round(
        (score / ((duration * target) / 7)) * 100
      )}%)`;
    } else if (type === EGoalType.cumulative) {
      topRightTag = 'Duration: ';
      topRightMsg = `${duration} days`;
      middleLeftTag = 'Total: ';
      middleLeftMsg = `${score} / ${target} ${units}`;
      middleRightTag = 'Goal Completion: ';
      middleRightMsg = `${Math.round((score / target) * 100)}%`;
    } else if (type === EGoalType.difference) {
      topRightTag = 'Duration: ';
      topRightMsg = `${duration} days`;
      middleLeftTag = 'Start: ';
      middleLeftMsg = `${initialValue!} ${units}`;
      middleRightTag = 'Goal: ';
      middleRightMsg = `${target} ${units}`;
      bottomLeftTag = 'Final: ';
      bottomLeftMsg = `${initialValue! + score} ${units}`;
      bottomRightTag = 'Change: ';
      bottomRightMsg = `${score > 0 ? '+' : ''}${score} ${units}`;
    }
    // TEST
  } else if (isStarted) {
    topLeftTag = 'Start Date: ';
    topLeftMsg = formattedDate;
    if (type === EGoalType.passfail) {
      middleLeftTag = 'Success To Date: ';
      middleLeftMsg = `${score} / ${time + 1} (${Math.round(
        (score / (time + 1)) * 100
      )}%)`;
      bottomLeftTag = 'Success Total: ';
      bottomLeftMsg = `${score} / ${(duration * target) / 7} (${Math.round(
        (score / ((duration * target) / 7)) * 100
      )}%)`;
    } else if (type === EGoalType.cumulative) {
      topRightTag = 'Day: ';
      topRightMsg = `${time + 1} / ${duration}`;
      middleLeftTag = 'Total: ';
      middleLeftMsg = `${score} / ${target} ${units}`;
      middleRightTag = 'Goal Completion: ';
      middleRightMsg = `${Math.round((score / target) * 100)}%`;
    } else if (type === EGoalType.difference) {
      topRightTag = 'Day: ';
      topRightMsg = `${time + 1} / ${duration}`;
      middleLeftTag = 'Start: ';
      middleLeftMsg = `${initialValue!} ${units}`;
      middleRightTag = 'Goal: ';
      middleRightMsg = `${target} ${units}`;
      bottomLeftTag = 'Current: ';
      bottomLeftMsg = `${initialValue! + score} ${units}`;
      bottomRightTag = 'Change: ';
      bottomRightMsg = `${score > 0 ? '+' : ''}${score} ${units}`;
    }
  } else {
    topLeftTag = 'Begins: ';
    topLeftMsg = formattedDateTime;
    topRightTag = 'Duration: ';
    topRightMsg = `${duration} days`;
    if (type === EGoalType.passfail) {
    } else if (type === EGoalType.cumulative) {
      middleLeftTag = 'Goal: ';
      middleLeftMsg = `${target} ${units}`;
    } else if (type === EGoalType.difference) {
      middleLeftTag = 'Start: ';
      middleLeftMsg = `${initialValue!} ${units}`;
      middleRightTag = 'Goal: ';
      middleRightMsg = `${target} ${units}`;
    }
  }

  return (
    <React.Fragment>
      {description && (
        <TableInfo>
          <p>
            <strong>Description: </strong>
            <WhiteSpaceSpan>{description}</WhiteSpaceSpan>
          </p>
        </TableInfo>
      )}
      <TableInfo>
        <div>
          <span>
            <strong>{topLeftTag}</strong>
            {topLeftMsg}
          </span>
          <span>
            <strong>{topRightTag}</strong>
            {topRightMsg}
          </span>
        </div>
      </TableInfo>
      {middleLeftTag === '' ? null : (
        <TableInfo>
          <div>
            <span>
              <strong>{middleLeftTag}</strong>
              {middleLeftMsg}
            </span>
            <span>
              <strong>{middleRightTag}</strong>
              {middleRightMsg}
            </span>
          </div>
        </TableInfo>
      )}
      {bottomLeftTag === '' ? null : (
        <TableInfo>
          <div>
            <span>
              <strong>{bottomLeftTag}</strong>
              {bottomLeftMsg}
            </span>
            <span>
              <strong>{bottomRightTag}</strong>
              {bottomRightMsg}
            </span>
          </div>
        </TableInfo>
      )}
    </React.Fragment>
  );
};

export default GoalInfo;
